-- Migration: Add auctions and bids tables for liquidation system
-- Date: 2026-06-22
--
-- NEUTERED (no-op): this file originally defined a second, incompatible
-- `auctions` schema (English-auction / sealed-bid design: borrower,
-- reserve_price, active, settled, highest_bidder, plus a separate `bids`
-- table) using `CREATE TABLE IF NOT EXISTS`.
--
-- 001_initial_setup.sql already creates `auctions` with a Dutch-auction
-- schema (borrower_address, current_price, recovery_rate, winning_bid,
-- winner, status) that is the one actually read/written by
-- internal/repository/postgres/auction.go. Because this file's CREATE
-- TABLE IF NOT EXISTS was a no-op against the pre-existing table, its own
-- `CREATE INDEX ... ON auctions(borrower)` failed with
-- "column borrower does not exist" on any fresh database applied in order.
--
-- No Go code ever referenced this file's `bids` table or its
-- reserve_price/active/collateral_transferred columns, so it was dead code.
-- Left in place (rather than deleted) for migration history/audit trail.
